language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install pytest
  - pip install cryptography
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install coverage coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coverage run --source pysyncobj -m py.test -v -l test_syncobj.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then py.test -v -l test_syncobj.py; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls -v; fi
